<?php include("header.php"); ?>
<div class="relative bg-gradient-to-br from-blue-950 to-indigo-950 text-white py-16 lg:py-32 overflow-hidden">
    <div class="container mx-auto px-4 pt-3 relative z-10">
        <div class="flex flex-col items-center justify-center text-center pt-5">
            <div class="lg:w-8/12">
                <h1 class="text-4xl lg:text-5xl font-bold mb-3 text-blue-900 dark:text-gray-100 pt-10" data-aos="fade-up">Terms of Use</h1>
                <h3 class="text-lg lg:text-xl font-extrabold text-blue-900 dark:text-gray-100 p-4">Version 1.0</h3>
                <div class="text-blue-900 dark:text-gray-100 p-4">
                    <p class="text-blue-900 dark:text-gray-100"><span class="text-blue-900 dark:text-gray-100">INTRODUCTION</span></p>
                    <p class="text-blue-900 dark:text-gray-100"><span class="text-blue-900 dark:text-gray-100">SUBJECT MATTER OF THE TERMS OF USE</span></p>
                    <p class="text-blue-900 dark:text-gray-100"><span class="text-blue-900 dark:text-gray-100">SIGN-UP</span></p>
                </div>
                <h6 class="text-sm text-blue-900 dark:text-gray-100">This Terms of Use is effective as of January 16, 2018.</h6>
            </div>
        </div>
    </div>
</div>

<div class="bg-gray-800 py-16">
    <div class="container mx-auto px-4">
        <div class="flex flex-wrap -mx-4">
            <div class="w-full px-4 py-8">
                <h2 class="text-2xl lg:text-3xl font-bold text-white mb-4">1. INTRODUCTION</h2>
                <p class="mb-4 text-gray-300">1.1 The service is made available to you by Octavat, a company formed under the laws of the United States of America (“Octavat”, “we”, “us” or “our”) through the website located at octavat.com, for the purpose of providing tools that allow managing personal cryptocurrency holdings. The term “you” or “Client” refers to the person visiting or otherwise accessing or using the Software.</p>
                <p class="mb-4 text-gray-300">1.2 These terms and conditions (“Terms of Use”) and the Privacy Policy (as defined below) govern your access to and use of the Software and constitute the entire, complete, and binding agreement between you and Octavat with respect to the Software.</p>
                <p class="mb-4 text-gray-300">1.4 THESE TERMS OF USE CONTAIN VERY IMPORTANT INFORMATION REGARDING YOUR RIGHTS AND OBLIGATIONS, AS WELL AS CONDITIONS, LIMITATIONS, AND EXCLUSIONS. PLEASE READ THESE TERMS OF USE CAREFULLY BEFORE ACCESSING OR USING THE SOFTWARE. BY USING THE SOFTWARE IN ANY WAY AND FOR ANY PURPOSE, WITH OR WITHOUT A CLIENT ACCOUNT AND FROM ANY DEVICE AND LOCATION, YOU AGREE AND CONFIRM</p>
                <p class="mb-4 text-gray-300">THAT:<br>
                    1.4.1 you have read and understood these Terms of Use and you accept and agree to be bound by these Terms of Use as they appear on each respective date that you use the Software.<br>
                    1.4.2 you assume all the obligations set forth herein;<br>
                    1.4.3 you are of sufficient legal age and capacity to use the Software;<br>
                    1.4.4 you are not under the control of jurisdiction that explicitly prohibits the use of similar software;<br>
                    1.4.5 you use the Software at your discretion and under your own responsibility.</p>
                <h2 class="text-2xl lg:text-3xl font-bold text-white mb-4">2. SUBJECT MATTER OF THE TERMS OF USE</h2>
                <p class="mb-4 text-gray-300">2.1 These Terms of Use apply between Octavat and the Client using the Software. The Software is made available to you via website https://Octavat on a computer or mobile device.<br>
                    2.2 These Terms of Use constitute a legally binding agreement between you and Octavat and cover the operation and provision of the Software. The Software is provided to natural and legal persons with an existing exchange account(s) and is intended to help better manage the personal cryptocurrency holdings. You shall not use the Software to manage a third-party’s cryptocurrency holdings in any way.<br>
                    2.3 Octavat may update or revise these Terms of Use from time to time by providing notice of such updates or revisions on the Software. Such changes to the Terms of Use will take effect as of the “Last updated” date stated at the beginning of these Terms of Use. Each time you access the Software, you agree to be bound by the most current version of the Terms of Use. You agree that you will review these Terms of Use periodically. If you do not agree to the terms of these Terms of Use or any modified version of these Terms of Use, your sole recourse is to terminate your use of the Software.
                </p>
                <h2 class="text-2xl lg:text-3xl font-bold text-white mb-4">3. SIGN-UP</h2>
                <p class="mb-4 text-gray-300">
                    3.1 In order to sign-up and use the Software, you must be at least eighteen (18) years of age.<br>
                    3.2 If you are entering into these Terms of Use on behalf of a legal person (i.e., company or other legal entity), you represent that you have the authority to bind such a legal person to these Terms of Use and that you have shared all email addresses, passwords, and access credentials with other authorized representatives of the legal person. If you do not have such authority, you shall not access or use the Software.<br>
                    3.3 Prior to the sign-up, you are solely responsible for ensuring that the use of the Software in accordance with these Terms of Use in your jurisdiction of residence is permitted by applicable laws. If such use is not permitted by laws, you shall not access or use the Software.<br>
                    3.4 The following steps are necessary to sign-up to create the Client Account and access the Software:<br>
                    3.4.1 Sign-up. Fill in the sign-up form by providing your email address and password. You will be given the opportunity to read the Terms of Use and the Privacy Policy. You can retrieve the documents from the named links and take notice of them. Prior to clicking “Register” to continue the sign-up process, you must confirm that you accept these Terms of Use and have acquainted yourself with our Privacy Policy. Further, you must confirm that you are at least 18 years old. After clicking “Register,” your account is created (“Client Account”). The same process applies in case you choose to sign-up with your Facebook account. The latter method requires you to also comply with the terms, conditions, and privacy policies of such third-party service.<br>
                    3.4.2 From the moment Octavat provides you the Client Account to access and use the Software, the sign-up process is completed. The Client Account is provided to you free of charge. Octavat has the right to refuse to provide you with a Client Account at its sole discretion, in which case you shall not use the Software.<br>
                    3.5 Entire Agreement The Agreement is the final, complete, and exclusive agreement of the parties with respect to the subject matter hereof and supersedes and merges all prior discussions between the parties with respect to such subject matter.<br>
                    Refund for the Subscription.<br>
                    <br>
                    If you wish to terminate your Subscription (as described in Section 14.5.1 of the Terms of Use) For Bot trading, each trade session will carry a trading fee of 25.5% from the total of investors earning. The trading fee will be paid in full according to the original deposit method. The fee will not be charged until 6 months when trading resets once the investor initiates transactions.<br><br>
                    Notes: Free to deposit. We only support several coins/tokens (Bitcoin, Ethereum, BNB, Tether usdt to deposit and will support more gradually.<br><br>
                    Asset recovery<br><br>
                    If you've accidentally sent an unsupported cryptocurrency to your Octavat account, it might still be recoverable. Please note that a network fee will be charged for this recovery attempt. The fee with a minimum charge of $60., you are entitled to a refund if you as a consumer from have informed us of using your right of withdrawal as described in Section 14.4.1 of the Terms of Use within seven (7) days since the purchase of the Subscription. The latter applies to consumers from any allowed jurisdictions. After the grace period of seven (7) days, a refund for the termination will not be provided. To receive a refund, you must contact support with a corresponding request, and you shall receive the refund in the same amount you have paid for the Subscription.<br><br>
                    You may take advantage of a refund for each disputed payment only once. If a refund is already made, then you shall have no right to further contest a refund request or dispute or transaction reversal with Octavat or a third-party payment service provider, bank, or financial institution.<br><br>
                    Refunds shall be made in the same currency you paid with or its equivalent based on the refund date market rate. Upon your prior approval, we may provide you with a discount for future services, an extra subscription period, or a subscription upgrade with a significantly greater benefit instead of a payment refund.<br><br>
                    Octavat is not responsible for any fees that may be applied by your payment service provider when processing a refund.<br><br>
                    The Right to Injunctive Relief<br><br>
                    Both you and we acknowledge that common law remedies for a breach of agreement or a possible breach of contract may be insufficient to cover all the losses that we sustain; therefore, in the event of a breach of contract or a possible breach of contract, the non-breaching party shall have the right to seek injunctive relief as well as all other remedies that are permitted under common law or equity.<br><br>
                    Limitation and Exemption of Liability<br><br>
                    1. You understand and agree that under no circumstance will we be held liable for any of the following events:<br>
                    1)loss of income;<br>
                    2)loss of transaction profits or contractual losses;<br>
                    3)disruption of the business<br>
                    4)loss of expected currency losses<br>
                    5)loss of information<br>
                    6)loss of opportunity, damage to goodwill or reputation<br>
                    7)damage or loss of data;<br>
                    8)cost of purchasing alternative products or services;<br>
                    9)any indirect, special or incidental loss or damage arising from any infringement (including negligence), breach of contract or any other cause, regardless of whether or not such loss or damage may reasonably be foreseen by us, and regardless of whether or not we are notified in advance of the possibility of such loss or damage.<br>
                    10)Items 1 to 9 above are independent of each other.<br><br>
                    2. You understand and agree that we shall not be held liable for any damages caused by any of the following events:<br>
                    1)Where we are properly justified in believing that your specific transactions may involve any serious violation or breach of law or agreement;<br>
                    2)Where we are reasonably justified in believing that your conduct on this Website is suspected of being illegal or immoral;<br>
                    3)The expenses and losses arising from the purchase or acquisition of any data, information, or transaction, etc. through the services offered by this Website;<br>
                    4)Your misunderstanding of the Services offered by this Website;<br>
                    5)Any other losses related to the services provided by this Website, which cannot be attributed to us.<br><br>
                    3. Where we fail to provide the Services or delay in providing such Services due to information network equipment maintenance, information network connectivity failures, errors in computer, communications or other systems, power failures, weather conditions, unexpected accidents, industrial actions, labor disputes, revolts, uprisings, riots, lack of productivity or production materials, fires, floods, storms, explosions, wars, failure on the part of banks or other partners, collapse of the digital asset market, actions by government, judicial or administrative authorities, other acts that are not within our control or beyond our inability to control, or due to causes on the part of third parties, we shall not assume any responsibility for such failure to provide service or delay in providing services, or for the resultant loss you may sustain as a result of such failure or delay.<br><br>
                    4. We cannot guarantee that all the information, programs, texts, etc. contained in this Website are completely safe, free from the interference and destruction by any malicious programs such as viruses, trojans, etc., therefore, your log-in to this Website or use of any services offered by this Website, download of any program, information, and data from this Website and your use thereof are your personal decisions and therefore you shall bear the any and all risks and losses that may possibly arise.<br><br>
                    5. We do not make any warranties and commitments in connection with any of the information, products, and business of any third-party websites linked to this Website, as well as any other forms of content that do not belong to us; your use of any of the services, information, and products provided by a third-party website is your personal decision and therefore you shall assume any and all the responsibilities arising therefrom.<br><br>
                    6. We do not make any explicit or implicit warranties regarding your use of the Services offered by this Website, including but not limited to the applicability, freedom from error or omission, consistency, accuracy, reliability, and applicability to a specific purpose, of the services provided by this Website. Furthermore, we do not make any commitment or guarantee in connection with the validity, accuracy, correctness, reliability, quality, stability, integrity, and timeliness of the technology and information covered by the services offered by this Website. Whether to log in to this Website or use the services provided by this Website is your personal decision and therefore you shall bear all the risks and possible losses arising from such a decision. We do not make any explicit or implicit warranties in connection with the market, value, and price of digital assets; you understand and acknowledge that the digital asset market is unstable, that the price and value of assets may fluctuate or collapse at any time, and that the transaction of digital assets is based on your personal free will and decision and therefore you shall assume any and all risks and losses that may possibly arise therefrom.<br><br>
                    7. The guarantees and undertakings specified in this Agreement shall be the only guarantee and statements that we make in connection with the Services provided by us under this Agreement and through this Website, and shall supersede any and all the warranties and commitments arising in any other way and manner, whether in writing or in words, express or implied. All these guarantees and statements represent only our own commitments and undertakings and do not guarantee any third party's compliance with the guarantees and commitments contained in this Agreement.<br><br>
                    8. We do not waive any of the rights not mentioned in this Agreement and to the maximum extent permitted by the applicable law, to limit, exempt, or offset our liability for damages.<br><br>
                    9. Upon your registration of your account with this Website, it shall be deemed that you approve any and all operations performed by us in accordance with the rules set forth in this Agreement, and any and all risks arising from such operations shall be assumed by you.<br><br>
                    Termination of Agreement<br><br>
                    10. This Website shall have the right to cancel your account with this Website anytime, and this Agreement shall be terminated on the date of the cancellation of your account.<br><br>
                    11. This Website shall have the right to terminate all Service offered by this Website to you anytime, and this Agreement shall terminate on the date of termination of all services offered by this Website to you.<br><br>
                    12. After the termination of this Agreement, you do not have the right to require this Website to continue to provide you with any service or perform any other obligation, including, but not limited to, requesting this Website to keep or disclose to you any information in your former original account, or to forward to you or any third party any information therein that is not read or sent.<br><br>
                    13. The termination of this Agreement shall not prevent the observant party from demanding the breaching party to assume other liabilities.<br><br>
                    You understand that this Website is only intended to serve as a venue for you to obtain digital asset information, find trading counterparties, smart bot trading, hold negotiations on and effect transactions of digital assets. This Website does not participate in any of your transactions, and therefore you shall, at your sole discretion, carefully assess the authenticity, legality, and validity of relevant digital assets and/or information, and solely bear the responsibilities and losses that may arise therefrom. All opinions, information, discussions, analyses, prices, advice, and other information on this Website are general market reviews and do not constitute any investment advice. We do not bear any loss arising directly or indirectly from reliance on the abovementioned information, including but not limited to, any loss of profits. The content of this Website may be changed from time to time and at any time without notice, and we have taken reasonable measures to ensure the accuracy of the information on the Website; however, we do not and cannot guarantee the degree of such accuracy, or bear any loss arising directly or indirectly from the information on this Website or from any delay or failure caused by failure to link up with the internet, transmit or receive any notice and information. Using internet-based trading systems also involves risks, including but not limited to failures in software, hardware, or Internet links, etc. In view of the fact that we cannot control the reliability and availability of the Internet, we will not be responsible for any distortion, delay, and link failure. octavat.com is the only official external information release platform for Octavat; It is prohibited to use this Website to engage in any illegal transaction activities, such as money laundering, smuggling, and commercial bribery. In the event that any of such activities is uncovered, this Website will adopt all available measures, including but not limited to freezing the offenders account, notifying relevant authorities, etc., and we will not assume any of the responsibilities arising therefrom and reserve the right to hold relevant persons accountable; It is prohibited to use this Website for the purpose of malicious manipulation of the market, improper transactions, or any other illicit trading activities. Where any of such illicit trading activities is uncovered, this Website will adopt such preventive and protective measures as warning, restricting trading, and closing accounts against any and all such malicious manipulation of prices, maliciously influencing the trading system and any other illicit behavior; we do not assume any of the responsibilities arising therefrom and reserve the right to hold relevant persons accountable.<br><br>
                    Affiliates please be informed of the following:<br><br>
                    If you are found to have invited registered users or committed other fraudulent acts, Octavat will cancel your affiliate status and adjust your commission percentage to 0%. If you are found to have offered commission higher than what Octavat would offer to others in secret, Octavat will cancel your affiliate status and adjust your commission percentage to 0%. If you are found to have tried to confuse users with phishing sites/pages that are similar to Octavat website/webpages, Octavat will cancel your affiliate status and adjust your commission percentage to 0%. You are not allowed to make any misleading statements, including, but not limited to, making any search engine optimization efforts using keywords like "Buy Octavat," "Octavat Login," "Octavat Official," and " Octavat P2P." Doing so will result in disqualification from rewards, and your affiliate status will be canceled. Octavat reserves the right to cancel an affiliate's status, revoke the right to receive commission, adjust the commission percentage to 0%, recover all commissions paid out, and file a claim for damages against the affiliate at any time if the affiliate does any damage to Octavat, defames Octavat, or otherwise acts against Octavat. This includes, but is not limited to, the following circumstances:<br>
                    1. Posting inaccurate information and negative comments about Octavat on social media platforms, including, but not limited to, Facebook, Instagram, and Twitter.<br>
                    2. Organizing a class action with financial claims against Trust.
                </p>
            </div>
            <p class="text-gray-300 w-full px-4 text-center">Effective Date: January 16, 2018</p>
        </div>
    </div>
</div>
<?php include("footer.php"); ?>